language: r

sudo: false

cache: packages

dist: bionic

os:
  - linux

jobs:
  include:

    - stage: Install package dependencies
      r: devel
      install:
        - ./bin/install_dependencies.sh
      script: true

    - stage: Install and check the package
      r: devel
      install: true
      script:
        - ./bin/install_and_check.sh

    - stage: Run tests
      r: devel
      install: true
      script:
        - ./bin/run_tests.sh

notifications:
  email:
    on_success: never
    on_failure: never
